### ISSUE TITLE
performance_adjust_up

### ISSUE THREAD

**Issue by tasoraso** [goranjovic55/Binance-Trading-Bot#45]
https://github.com/goranjovic55/Binance-Trading-Bot/blob/37fd4ce788c3ecccc3fadf614b413894ee092455/Binance_Detect_Moonings.py#L760

DYNAMIC_WIN_LOSS_UP and not DYNAMIC_WIN_LOSS_DOWN in both line 760 and 761

**Comment by goranjovic55** [comment]
fixed TY
