### ISSUE TITLE
Stop Loss Bug

### ISSUE THREAD

**Issue by chromatic6** [goranjovic55/Binance-Trading-Bot#77]
Hi,

Stop Loss don't work as expected. I start a test session with default parameters in config.yml (STOP_LOSS: 3)

The "STOP_LOSS" variable in session_info.json is filled with strange numbre like this:
```
4433.675640106201
9683876534.500877
4.759015155419072e+16
3.034450382939706e+25
6.132429670462307e+74
6.6884224795857e+193
```

On first buy of some coins the SL start with huge numbers:
`TP:1.28:2.39 or SL:-4484690756570124023740448572080896602373552377797895937321755711979170249294191028339175364001004076712027837302784460278942709748430728250434827881423120834402557335323044126654464.00:-359321429097838669505640101637343327859453470871260005056995556301422959179011934669454782998943547413225179896825135179135730388922616458931735518059590156283531749735606361497010176.00 not yet reached, not selling ADAUSDT for now >> Bought at: 1.24810000 - Now: 1.24460000 : -0.28% Est: -0.06 USDT - CIP: -0.63/-0.51 - TAKE_PROFIT: 2.39`

Eventually after a while the SL in both session_info.json and in test_coins_bought.json (or coins_bought.json) stay stuck on NaN

So there's no stop loss at all and only the TRAILING_STOP_LOSS trigger a change from NaN to a normal value.

**Comment by mopschond** [comment]
trade.py Line: 257
`coinStopLoss = BUY_PRICE + ((BUY_PRICE * coins_bought[coin]['stop_loss']) / 100)`

I may be wrong but shouldn't it be a substraction?

**Comment by goranjovic55** [comment]
fixed in latest version
